[package]
name = "basic_bitcoin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = {version ="0.27.0", features = ["rand-std"]}
rand = "0.8.5"
num = "0.4.0"
num-traits = "0.2.15"